FROM python:3.7-alpine
MAINTAINER AnhLT59.

ENV PYTHONUNBUFFERED 1
ENV ENV DEV

# Install dependencies
COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

# Setup directory structure
RUN mkdir /app
WORKDIR /app
COPY ./app/ /test

CMD exec python3 manage.py runserver